name: golang test
on: [pull_request]
jobs:
  test:
    name: runner / go test and coverage
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.x
    - name: test
      run: go test ./...
    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v1
      with:
        golangci_lint_flags: "--modules-download-mode=readonly --config=.golangci.yml"
        level: info

